CONFIG_MBOX=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_ISR_STACK_SIZE=64
CONFIG_IDLE_STACK_SIZE=32
CONFIG_OUTPUT_DISASSEMBLY=y
# BIST tests to run on the LP core
CONFIG_ESP_BIST=y
CONFIG_ESP_BIST_CPU_REG_TEST=y
CONFIG_ESP_BIST_MEMORY_RAM_TEST=y
CONFIG_ESP_BIST_MEMORY_FLASH_TEST=y
