############################################################################
# samples/nuttx/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

MENUDESC = "ESP-BIST"

include $(APPDIR)/Directory.mk
