############################################################################
# tests/integration/hd_nuttx/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

MENUDESC = "ESP-BIST HD fail-closed"

include $(APPDIR)/Directory.mk
